######################## default configuration ####################
baseURL = "/"
title = "Halcyon IDE :: An IDE for Nmap Script Developers"
theme = "godocs-hugo"
# disable language
disableLanguages = [] # desable language from here

# hugo outputs
[outputs]
home = [ "HTML", "RSS", "JSON"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/match-height/jquery.matchHeight-min.js"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Documentation"
url = "/getting-started/"
weight = 1

[[menu.main]]
name = "FAQ"
url = "/faq/"
weight = 2

[[menu.main]]
name = "Download"
url = ""
weight = 3

[[menu.main]]
parent = "Download"
name = "Binary [jar]"
url = "https://github.com/s4n7h0/Halcyon-IDE/releases/download/v2.0.2/Halcyon_IDE_v2.0.2.jar"
weight = 1

[[menu.main]]
parent = "Download"
name = "Source [zip]"
url = "https://github.com/s4n7h0/Halcyon-IDE/archive/v2.0.2.zip"
weight = 2

[[menu.main]]
parent = "Download"
name = "Source [tar.gz]"
url = "https://github.com/s4n7h0/Halcyon-IDE/archive/v2.0.2.tar.gz"
weight = 3

# footer menu
[[menu.footer]]
name = "Changelog"
url = "changelog"
weight = 1

[[menu.footer]]
name = "contact"
url = "contact"
weight = 2 


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Sanoop Thomas (s4n7h0)"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button bordered
[params.navigation_button_bordered]
enable = true
label = "changelog"
link = "changelog"

# Navigation button solid
[params.navigation_button_solid]
enable = true
label = "contact"
link = "contact"

  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/HalcyonIDE/"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/Halcyon_IDE"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/s4n7h0/Halcyon"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
# copyright
copyright = " [Halcyon IDE](https://halcyon-ide.org)"

# banner
[Languages.en.banner]
title = "An IDE for Nmap Script Development"
subtitle = "Halcyon IDE is the first Integrated Development Environment released exclusively for Nmap script development."
image = "images/banner.png"

# call to action
[Languages.en.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
image = "images/question.png"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

  # call to action button
  [Languages.en.call_to_action.button]
  enable = "true"
  label = "Submit a ticket"
  link = "contact"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"

# banner
[Languages.fr.banner]
title = "Documentation Theme By Themefisher Team"
subtitle = "Lorem ipsum dolor amet, consetetur sadiffspscing elitr, diam nonumy invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua At."
image = "images/banner.jpg"

# call to action
[Languages.fr.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
image = "images/cta-illustration.jpg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

  # call to action button
  [Languages.fr.call_to_action.button]
  enable = "true"
  label = "Submit a ticket"
  link = "contact"